name: Build

on:
  push:
    branches:
       - 'main'   # Trigger on pushes to any branch
 


jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Publish Module to PowerShell Gallery
      uses: pcgeek86/publish-powershell-module-action@v20
      id: publish-module
      with:
        NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}